name: Makefile CI

env:
  GO111MODULE: "on"

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ~1.17

    - name: Check out code
      uses: actions/checkout@v3

    - name: Linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.41.1
      
    - name: make build
      run: make build

#    - name: make test
#      run: make test

    - name: make test-race
      run: make test